name: Deploy Lambda Function

on:
  push:
    branches: [master]

permissions:
  id-token: write # this is required for requesting the JWT for OIDC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          role-to-assume: arn:aws:iam::648295097384:role/github_actions_heyparkerj_role
          aws-region: us-west-2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11" 
      # - name: Set up Poetry
      #   run: |
      #     export POETRY_HOME=/opt/poetry
      #     python3 -m venv $POETRY_HOME
      #     $POETRY_HOME/bin/pip install poetry==1.2.0
      #     $POETRY_HOME/bin/poetry --version
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true
      - name: Build Project
        run: |
          poetry install --only main --sync --no-interaction
          poetry build
          poetry run pip install --upgrade -t package dist/*.whl
          cd package ; zip -r ../dist/artifact.zip . -x '*.pyc'
      - name: Upload the ZIP file to S3
        run : |
          ls -laF ./dist
          aws s3 sync ./dist s3://sleeper-data-pipeline-backfill-bucket --delete
